### ISSUE TITLE
[CRASH]

### ISSUE THREAD

**Issue by Miningav** [CalaMariGold/Rebirth-Of-The-Night#100]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
When I click play, it will load, exit the menu like normal, but instead of popping up minecraft and loading the mods it just gives me a crash.

**To Reproduce**
I downloaded off curse, since twitch wont let me, imported the zip file to twitch, downloaded it from there, added optifine to mods, opened the game. It worked last time I installed it like that.

**Crash Log**
[21:20:16] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:20:16] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[21:20:16] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[21:20:16] [main/INFO]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[21:20:16] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Miningav\Twitch\Minecraft\Install\runtime\jre-x64
[21:20:20] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[21:20:20] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[21:20:20] [main/INFO]: Searching C:\Users\Miningav\Twitch\Minecraft\Instances\Rebirth of the Night\mods for mods
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in B3M-1.12.2-15.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod sedridor.B3M.core.B3M_CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod B3M_CorePlugin (sedridor.B3M.core.B3M_CorePlugin) is not signed!
[21:20:20] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in BetterWithLib-1.12-1.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod LoadingPlugin (betterwithmods.library.core.LoadingPlugin) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Bloodmoon-MC1.12.2-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Blur-1.0.4-14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod com.tterrag.blur.BlurPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod BlurPlugin (com.tterrag.blur.BlurPlugin) is not signed!
[21:20:20] [main/WARN]: The coremod com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod BNBGamingCore (com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Born In A Barn V1.8-1.12-1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod com.chocohead.biab.BornInABarn does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod Born in a Barn (com.chocohead.biab.BornInABarn) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Charm-1.12.2-1.3.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod svenhjol.charm.base.CharmLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod CharmLoadingPlugin (svenhjol.charm.base.CharmLoadingPlugin) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ChunkAnimator-MC1.12-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod lumien.chunkanimator.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod LoadingPlugin (lumien.chunkanimator.asm.LoadingPlugin) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.1.30.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CustomLoadingScreen-1.12.2-1.4.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod ClsPlugin (alexiil.mc.mod.load.coremod.ClsPlugin) is not signed!
[21:20:20] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.0.2.jar
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.10-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in future-mc-0.1.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod FutureMC (thedarkcolour.futuremc.asm.CoreLoader) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HardcoreDarkness-MC1.12.2-2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[21:20:20] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[21:20:20] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.5.1.jar
[21:20:20] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from movingworld-1.12-6.342-full.jar
[21:20:20] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F4.jar
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-177.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[21:20:20] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in rats-3.2.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod ratscore (com.github.alexthe666.rats.server.asm.RatsPlugin) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in rebind-1.12.2-2.7.5-0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in redstonepaste-mc1.12-1.7.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod NWRTweak (net.fybertech.nwr.NWRTweak) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SereneSeasons-1.12.2-1.2.18-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod sereneseasons.asm.SSLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod SSLoadingPlugin (sereneseasons.asm.SSLoadingPlugin) is not signed!
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SmoothFont-mc1.12.2-2.1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:20] [main/WARN]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
[21:20:20] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Surge-1.12.2-2.0.77.jar
[21:20:20] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-99.jar
[21:20:20] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in VerticallyStackedDimensions-1.12.2-0.1.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[21:20:20] [main/WARN]: The coremod Vertically Stacked Dimensions ASM (cd4017be.dimstack.asm.CorePlugin) is not signed!
[21:20:20] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:20:20] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[21:20:20] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[21:20:20] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Miningav/Twitch/Minecraft/Instances/Rebirth%20of%20the%20Night/mods/DynamicSurroundings-1.12.2-3.6.0.2.jar Service=LaunchWrapper Env=CLIENT
[21:20:20] [main/DEBUG]: Instantiating coremod class TransformLoader
[21:20:20] [main/DEBUG]: The coremod org.orecruncher.dsurround.mixins.TransformLoader requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[21:20:20] [main/DEBUG]: Found signing certificates for coremod TransformLoader (org.orecruncher.dsurround.mixins.TransformLoader)
[21:20:20] [main/DEBUG]: Found certificate 7a2128d395ad96ceb9d9030fbd41d035b435753a
[21:20:21] [main/INFO]: Compatibility level set to JAVA_8
[21:20:21] [main/DEBUG]: Enqueued coremod TransformLoader
[21:20:21] [main/DEBUG]: Instantiating coremod class MalisisCorePlugin
[21:20:21] [main/WARN]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:21] [main/WARN]: The coremod MalisisCorePlugin (net.malisis.core.asm.MalisisCorePlugin) is not signed!
[21:20:21] [main/DEBUG]: Enqueued coremod MalisisCorePlugin
[21:20:21] [main/DEBUG]: Instantiating coremod class MovingWorldCoreMod
[21:20:21] [main/TRACE]: coremod named MovingWorldCore is loading
[21:20:21] [main/WARN]: The coremod com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[21:20:21] [main/WARN]: The coremod MovingWorldCore (com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod) is not signed!
[21:20:21] [main/ERROR]: Mixin config mixins.movingworld.json does not specify "minVersion" property
[21:20:21] [main/DEBUG]: Enqueued coremod MovingWorldCore
[21:20:21] [main/DEBUG]: Instantiating coremod class SurgeLoadingPlugin
[21:20:21] [main/DEBUG]: The coremod net.darkhax.surge.core.SurgeLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[21:20:21] [main/DEBUG]: Found signing certificates for coremod SurgeLoadingPlugin (net.darkhax.surge.core.SurgeLoadingPlugin)
[21:20:21] [main/DEBUG]: Found certificate d476d1b22b218a10d845928d1665d45fce301b27
[21:20:21] [main/DEBUG]: Enqueued coremod SurgeLoadingPlugin
[21:20:21] [main/DEBUG]: Instantiating coremod class VanillaFixLoadingPlugin
[21:20:21] [main/INFO]: Initializing VanillaFix
[21:20:21] [main/INFO]: Initializing StacktraceDeobfuscator
[21:20:21] [main/INFO]: Found MCP method mappings: methods-stable_39.csv
[21:20:21] [main/INFO]: Done initializing StacktraceDeobfuscator
[21:20:21] [main/INFO]: Initializing Bug Fix Mixins
[21:20:21] [main/INFO]: Initializing Crash Fix Mixins
[21:20:21] [main/INFO]: Initializing Profiler Improvement Mixins
[21:20:21] [main/INFO]: Initializing Texture Fix Mixins
[21:20:21] [main/INFO]: Initializing Mod Support Mixins
[21:20:21] [main/DEBUG]: The coremod org.dimdev.vanillafix.VanillaFixLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[21:20:21] [main/WARN]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[21:20:21] [main/DEBUG]: Enqueued coremod VanillaFixLoadingPlugin
[21:20:21] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:20:21] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:20:21] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[21:20:21] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:20:21] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[21:20:21] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[21:20:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:20:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[21:20:21] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[21:20:21] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[21:20:21] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[21:20:21] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[21:20:21] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\Miningav\Twitch\Minecraft\Instances\Rebirth of the Night\mods\OptiFine_1.12.2_HD_U_F4.jar
[21:20:21] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[21:20:21] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[21:20:21] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[21:20:21] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[21:20:21] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[21:20:21] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[21:20:21] [main/DEBUG]: Injection complete
[21:20:21] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[21:20:21] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[21:20:22] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[21:20:22] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:169) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:114) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:77) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:164) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 2 more
[21:20:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:20:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:20:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[21:20:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[21:20:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[21:20:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[21:20:22] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Info (please complete the following information):**
 - Modpack Version: 2.76.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.76.1

Please e-mail at gcmagill13@gmail.com if possible.

**Comment by CalaMariGold** [comment]
`[21:20:22] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.`

Reinstall Minecraft, Twitch and the modpack.

May also be an issue with your firewall/virus checker.
