### ISSUE TITLE
[CRASH] Launcher won't launch game

### ISSUE THREAD

**Issue by indiedeedz** [CalaMariGold/Rebirth-Of-The-Night#242]
ISSUES NOT USING OUR TEMPLATE WILL NOT BE CONSIDERED AND WILL BE CLOSED!

**Describe the crash**
Every time I click play on the launcher it'll close then reopen with a crash log. I have tried deleting and reinstalling ROTN a good few times but nothing is working.

**To Reproduce**

- Hit play from twitch
- Hit play on launcher
- Crashes

**Crash Log**

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[19:35:29] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:35:29] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:35:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:35:29] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[19:35:29] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Mac OS X:x86_64:10.13.6, installed at /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre
[19:35:32] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[19:35:32] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[19:35:32] [main/INFO] [FML]: Searching /Volumes/My Passport for Mac 1/GAMES/Twitch/Instances/Rebirth of the Night/mods for mods
[19:35:32] [main/INFO] [FML]: Searching /Volumes/My Passport for Mac 1/GAMES/Twitch/Instances/Rebirth of the Night/mods/1.12.2 for mods
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[19:35:32] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from arcanearchives-0.2.0.17.jar
[19:35:32] [main/INFO] [FML]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in BetterWithLib-1.12-1.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod LoadingPlugin (betterwithmods.library.core.LoadingPlugin) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Blur-1.0.4-14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod com.tterrag.blur.BlurPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod BlurPlugin (com.tterrag.blur.BlurPlugin) is not signed!
[19:35:32] [main/WARN] [FML]: The coremod com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod BNBGamingCore (com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Born In A Barn V1.8-1.12-1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod com.chocohead.biab.BornInABarn does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod Born in a Barn (com.chocohead.biab.BornInABarn) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Charm-1.12.2-1.3.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod svenhjol.charm.base.CharmLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod CharmLoadingPlugin (svenhjol.charm.base.CharmLoadingPlugin) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ChunkAnimator-MC1.12-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod lumien.chunkanimator.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod LoadingPlugin (lumien.chunkanimator.asm.LoadingPlugin) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CustomLoadingScreen-1.12.2-1.4.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod ClsPlugin (alexiil.mc.mod.load.coremod.ClsPlugin) is not signed!
[19:35:32] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.1.0.jar
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in enchcontrol-1.12.2-1.1.5-0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.10-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in future-mc-0.1.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod FutureMC (thedarkcolour.futuremc.asm.CoreLoader) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in HardcoreDarkness-MC1.12.2-2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[19:35:32] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:32] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:35:32] [main/WARN] [FML]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[19:35:33] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from movingworld-1.12-6.342-full.jar
[19:35:33] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in NonUpdate-AllMCVersion-Final-2.0.2-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:35:33] [main/INFO] [NonUpdate]: Load file: nu-whitelist.txt
[19:35:33] [main/INFO] [NonUpdate]: minecraft.net
[19:35:33] [main/INFO] [NonUpdate]: mojang.com
[19:35:33] [main/INFO] [NonUpdate]: skin.prinzeugen.net
[19:35:33] [main/INFO] [NonUpdate]: fleey.org
[19:35:33] [main/INFO] [NonUpdate]: www.skinme.cc
[19:35:33] [main/INFO] [STDOUT]: [nonupdate.forge.ReflectionHelper:resetReflection:52]: Try getDeclaredFields: getDeclaredFields0(boolean)
[19:35:33] [main/INFO] [STDOUT]: [nonupdate.forge.ReflectionHelper:<clinit>:19]: Try getField: reflectionData
[19:35:33] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at /Volumes/My Passport for Mac 1/GAMES/Twitch/Instances/Rebirth of the Night for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at nonupdate.forge.NonUpdate.<clinit>(NonUpdate.java:85) ~[NonUpdate-AllMCVersion-Final-2.0.2-universal.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 5 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: java.lang.Class.classLoader
	at nonupdate.forge.ReflectionHelper.getField(ReflectionHelper.java:101) ~[ReflectionHelper.class:?]
	at nonupdate.forge.ReflectionHelper.<clinit>(ReflectionHelper.java:35) ~[ReflectionHelper.class:?]
	at nonupdate.forge.NonUpdate.<clinit>(NonUpdate.java:85) ~[NonUpdate-AllMCVersion-Final-2.0.2-universal.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 5 more
Caused by: java.lang.NoSuchFieldException: java.lang.Class.classLoader
	at nonupdate.forge.ReflectionHelper.getField(ReflectionHelper.java:101) ~[ReflectionHelper.class:?]
	at nonupdate.forge.ReflectionHelper.<clinit>(ReflectionHelper.java:35) ~[ReflectionHelper.class:?]
	at nonupdate.forge.NonUpdate.<clinit>(NonUpdate.java:85) ~[NonUpdate-AllMCVersion-Final-2.0.2-universal.jar:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2847.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2847.jar:?]
	... 5 more
Exception in thread "main" [19:35:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[19:35:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[19:35:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[19:35:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[19:35:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[19:35:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[19:35:33] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Info (please complete the following information):**
 - Modpack Version: 2.77.1
 - Server or Singleplayer: Singleplayer
 - Version the world was created on: 2.77.1

**Additional context**
Add any other context about the problem here and your thoughts about what could have caused it.

**Comment by CalaMariGold** [comment]
This doesn't have anything to do with the modpack. Do a google search of the error

**Comment by indiedeedz** [comment]
Can you at least tell me what the error is?

**Comment by Foreck1** [comment]
You could've just copypasted the **first** line of your problem in google...
[here](https://lmgtfy.com/?q=java+hotspot(tm)+64-bit+server+vm+warning+ignoring+option+permsize%3D256m+support+was+removed+in+8.0)
