### ISSUE TITLE
[CRASH] Optifine Emissive Textures Crash

### ISSUE THREAD

**Issue by SandwichHorror** [CalaMariGold/Rebirth-Of-The-Night#42]
**Describe the bug**
Instant CTD when near Skyroot chests that generated naturally

**To Reproduce**
Generate Aether world. Fly around near dungeon. Crash to desktop.

**Expected behavior**
Not crash to desktop.

**Info (please complete the following information):**
 - Modpack Version: v2.74
 - Server or Singleplayer: Singleplayer 
 - Version the world was created on: 1.12.2

`[23:59:38] [Client thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering Block Entity
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:207) ~[bwx.class:?]
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:154) ~[bwx.class:?]
at net.minecraft.client.renderer.RenderGlobal.redirect$tileEntityRender$zcm000(RenderGlobal.java:3741) ~[buy.class:?]
at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:1031) ~[buy.class:?]
at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1800) ~[buq.class:?]
at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1613) ~[buq.class:?]
at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1384) ~[buq.class:?]
at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[bib.class:?]
at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
at net.optifine.EmissiveTextures.getEmissiveTexture(EmissiveTextures.java:96) ~[EmissiveTextures.class:?]
at net.minecraft.client.renderer.texture.TextureManager.bindTexture(TextureManager.java:54) ~[cdr.class:?]
at net.minecraft.client.renderer.tileentity.TileEntitySpecialRenderer.bindTexture(TileEntitySpecialRenderer.java:64) ~[bwy.class:?]
at com.legacy.aether.addon.client.renders.blocks.SkyrootChestRenderer.render(SkyrootChestRenderer.java:69) ~[SkyrootChestRenderer.class:?]
at com.legacy.aether.addon.client.renders.blocks.SkyrootChestRenderer.render(SkyrootChestRenderer.java:19) ~[SkyrootChestRenderer.class:?]
at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.render(TileEntityRendererDispatcher.java:198) ~[bwx.class:?]`

**Comment by CalaMariGold** [comment]
Should mention that this doesn't always happen. It feels pretty random to be honest. A temporary fix is to disable emissive/connected textures in Optifine video settings.

**Comment by SandwichHorror** [comment]
I have experienced it every time I visit the Aether, to the point where I can't even test out the bosses.

**Comment by CalaMariGold** [comment]
I haven't experienced it a single time myself. I've flown around quite a lot too.

**Comment by CalaMariGold** [comment]
I noticed a few other blocks cause this issue. I may disable emissive textures completely in 2.75.2 in order to fix this issue. Can someone look into the new Optifine version and see if it fixed it?

**Comment by CalaMariGold** [comment]
Fixed in 2.75.2 by disabling emissive textures. Will re-enable if Optifine fixes this in an update.

https://github.com/CalaMariGold/Rebirth-Of-The-Night/commit/4f4e36ea8f35a0a6946e01dc53b3113ca0c458b7
