### ISSUE TITLE
[BUG] Game crashes before forge loading screen

### ISSUE THREAD

**Issue by PrivatePile38** [CalaMariGold/Rebirth-Of-The-Night#63]
**Describe the bug**
The game crashes before the forge loading screen

**To Reproduce**
Unsure

**Expected behavior**
The game not to crash

**Screenshots**

**Info (please complete the following information):**
 - Modpack Version: 2.75.3
 - Server or Singleplayer: Single
 - Version the world was created on: 2.75.1

**Additional context**
CRASH REPORT BELOW
[18:48:38] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:48:38] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:48:38] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:48:38] [main/INFO]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[18:48:38] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Private_Pile\Twitch\Minecraft\Install\runtime\jre-x64
[18:48:38] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[18:48:38] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[18:48:38] [main/INFO]: Searching C:\Users\Ben Morrow\Twitch\Minecraft\Instances\Rebirth of the Night\mods for mods
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in B3M-1.12.2-15.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod sedridor.B3M.core.B3M_CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod B3M_CorePlugin (sedridor.B3M.core.B3M_CorePlugin) is not signed!
[18:48:38] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in BetterWithLib-1.12-1.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod LoadingPlugin (betterwithmods.library.core.LoadingPlugin) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Bloodmoon-MC1.12.2-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Blur-1.0.4-14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod com.tterrag.blur.BlurPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod BlurPlugin (com.tterrag.blur.BlurPlugin) is not signed!
[18:48:38] [main/WARN]: The coremod com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod BNBGamingCore (com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Born In A Barn V1.8-1.12-1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod com.chocohead.biab.BornInABarn does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod Born in a Barn (com.chocohead.biab.BornInABarn) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Charm-1.12.2-1.3.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod svenhjol.charm.base.CharmLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod CharmLoadingPlugin (svenhjol.charm.base.CharmLoadingPlugin) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ChunkAnimator-MC1.12-1.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod lumien.chunkanimator.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod LoadingPlugin (lumien.chunkanimator.asm.LoadingPlugin) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.1.30.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CustomLoadingScreen-1.12.2-1.4.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod ClsPlugin (alexiil.mc.mod.load.coremod.ClsPlugin) is not signed!
[18:48:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from DynamicSurroundings-1.12.2-3.6.0.2.jar
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.10-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in future-mc-0.1.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod FutureMC (thedarkcolour.futuremc.asm.CoreLoader) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in HardcoreDarkness-MC1.12.2-2.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod lumien.hardcoredarkness.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[18:48:38] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[18:48:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.5.1.jar
[18:48:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from movingworld-1.12-6.342-full.jar
[18:48:38] [main/INFO]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F4.jar
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-177.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[18:48:38] [main/WARN]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in rebind-1.12.2-2.7.5-0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in redstonepaste-mc1.12-1.7.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod NWRTweak (net.fybertech.nwr.NWRTweak) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SereneSeasons-1.12.2-1.2.18-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod sereneseasons.asm.SSLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod SSLoadingPlugin (sereneseasons.asm.SSLoadingPlugin) is not signed!
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SmoothFont-mc1.12.2-2.1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:38] [main/WARN]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
[18:48:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from Surge-1.12.2-2.0.77.jar
[18:48:38] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from VanillaFix-1.0.10-99.jar
[18:48:38] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in VerticallyStackedDimensions-1.12.2-0.1.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:48:38] [main/WARN]: The coremod Vertically Stacked Dimensions ASM (cd4017be.dimstack.asm.CorePlugin) is not signed!
[18:48:38] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:48:38] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[18:48:38] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[18:48:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/C:/Users/Ben%20Morrow/Twitch/Minecraft/Instances/Rebirth%20of%20the%20Night/mods/DynamicSurroundings-1.12.2-3.6.0.2.jar Service=LaunchWrapper Env=CLIENT
[18:48:39] [main/DEBUG]: Instantiating coremod class TransformLoader
[18:48:39] [main/DEBUG]: The coremod org.orecruncher.dsurround.mixins.TransformLoader requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[18:48:39] [main/DEBUG]: Found signing certificates for coremod TransformLoader (org.orecruncher.dsurround.mixins.TransformLoader)
[18:48:39] [main/DEBUG]: Found certificate 7a2128d395ad96ceb9d9030fbd41d035b435753a
[18:48:39] [main/INFO]: Compatibility level set to JAVA_8
[18:48:39] [main/DEBUG]: Enqueued coremod TransformLoader
[18:48:39] [main/DEBUG]: Instantiating coremod class MalisisCorePlugin
[18:48:39] [main/WARN]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:39] [main/WARN]: The coremod MalisisCorePlugin (net.malisis.core.asm.MalisisCorePlugin) is not signed!
[18:48:39] [main/DEBUG]: Enqueued coremod MalisisCorePlugin
[18:48:39] [main/DEBUG]: Instantiating coremod class MovingWorldCoreMod
[18:48:39] [main/TRACE]: coremod named MovingWorldCore is loading
[18:48:39] [main/WARN]: The coremod com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:48:39] [main/WARN]: The coremod MovingWorldCore (com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod) is not signed!
[18:48:39] [main/ERROR]: Mixin config mixins.movingworld.json does not specify "minVersion" property
[18:48:39] [main/DEBUG]: Enqueued coremod MovingWorldCore
[18:48:39] [main/DEBUG]: Instantiating coremod class SurgeLoadingPlugin
[18:48:39] [main/DEBUG]: The coremod net.darkhax.surge.core.SurgeLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[18:48:39] [main/DEBUG]: Found signing certificates for coremod SurgeLoadingPlugin (net.darkhax.surge.core.SurgeLoadingPlugin)
[18:48:39] [main/DEBUG]: Found certificate d476d1b22b218a10d845928d1665d45fce301b27
[18:48:39] [main/DEBUG]: Enqueued coremod SurgeLoadingPlugin
[18:48:39] [main/DEBUG]: Instantiating coremod class VanillaFixLoadingPlugin
[18:48:39] [main/INFO]: Initializing VanillaFix
[18:48:39] [main/INFO]: Initializing StacktraceDeobfuscator
[18:48:39] [main/INFO]: Found MCP method mappings: methods-stable_39.csv
[18:48:39] [main/INFO]: Done initializing StacktraceDeobfuscator
[18:48:39] [main/INFO]: Initializing Bug Fix Mixins
[18:48:39] [main/INFO]: Initializing Crash Fix Mixins
[18:48:39] [main/INFO]: Initializing Profiler Improvement Mixins
[18:48:39] [main/INFO]: Initializing Texture Fix Mixins
[18:48:39] [main/INFO]: Initializing Mod Support Mixins
[18:48:39] [main/DEBUG]: The coremod org.dimdev.vanillafix.VanillaFixLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[18:48:39] [main/WARN]: The coremod VanillaFixLoadingPlugin (org.dimdev.vanillafix.VanillaFixLoadingPlugin) is not signed!
[18:48:39] [main/DEBUG]: Enqueued coremod VanillaFixLoadingPlugin
[18:48:39] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[18:48:39] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[18:48:39] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[18:48:39] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[18:48:39] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[18:48:39] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:48:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:48:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:48:39] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[18:48:39] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[18:48:39] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[18:48:39] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[18:48:39] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Users\Ben Morrow\Twitch\Minecraft\Instances\Rebirth of the Night\mods\OptiFine_1.12.2_HD_U_F4.jar
[18:48:39] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:39] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[18:48:39] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[18:48:39] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[18:48:39] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[18:48:39] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[18:48:39] [main/DEBUG]: Injection complete
[18:48:39] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[18:48:39] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[18:48:40] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:48:40] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[18:48:40] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:40] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[18:48:40] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:40] [main/DEBUG]: Injecting coremod CharmLoadingPlugin \{svenhjol.charm.base.CharmLoadingPlugin\} class transformers
[18:48:40] [main/TRACE]: Registering transformer svenhjol.charm.base.CharmClassTransformer
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for CharmLoadingPlugin \{svenhjol.charm.base.CharmLoadingPlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin CharmLoadingPlugin
[18:48:40] [main/DEBUG]: Coremod plugin class CharmLoadingPlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:40] [main/DEBUG]: Injecting coremod ForgelinPlugin \{net.shadowfacts.forgelin.preloader.ForgelinPlugin\} class transformers
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for ForgelinPlugin \{net.shadowfacts.forgelin.preloader.ForgelinPlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin ForgelinPlugin
[18:48:40] [main/DEBUG]: Coremod plugin class ForgelinPlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:40] [main/DEBUG]: Injecting coremod IvToolkit \{ivorius.ivtoolkit.IvToolkitLoadingPlugin\} class transformers
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for IvToolkit \{ivorius.ivtoolkit.IvToolkitLoadingPlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin IvToolkit
[18:48:40] [main/DEBUG]: Coremod plugin class IvToolkitLoadingPlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:40] [main/DEBUG]: Injecting coremod ReBind Core \{austeretony.rebind.common.core.ReBindCorePlugin\} class transformers
[18:48:40] [main/TRACE]: Registering transformer austeretony.rebind.common.core.ReBindClassTransformer
[18:48:40] [main/INFO]: External config up-to-date!
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for ReBind Core \{austeretony.rebind.common.core.ReBindCorePlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin ReBind Core
[18:48:40] [main/DEBUG]: Coremod plugin class ReBindCorePlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:40] [main/DEBUG]: Injecting coremod SSLoadingPlugin \{sereneseasons.asm.SSLoadingPlugin\} class transformers
[18:48:40] [main/TRACE]: Registering transformer sereneseasons.asm.transformer.EntityRendererTransformer
[18:48:40] [main/TRACE]: Registering transformer sereneseasons.asm.transformer.WorldTransformer
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for SSLoadingPlugin \{sereneseasons.asm.SSLoadingPlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin SSLoadingPlugin
[18:48:40] [main/DEBUG]: Coremod plugin class SSLoadingPlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:40] [main/DEBUG]: Injecting coremod CorePlugin \{bre.smoothfont.asm.CorePlugin\} class transformers
[18:48:40] [main/TRACE]: Registering transformer bre.smoothfont.asm.Transformer
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for CorePlugin \{bre.smoothfont.asm.CorePlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin CorePlugin
[18:48:40] [main/INFO]: OptiFine was detected.
[18:48:40] [main/DEBUG]: Coremod plugin class CorePlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[18:48:40] [main/ERROR]: Mixin config mixins.movingworld.json does not specify "minVersion" property
[18:48:40] [main/INFO]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@165e389b
[18:48:40] [main/DEBUG]: Injecting coremod TransformLoader \{org.orecruncher.dsurround.mixins.TransformLoader\} class transformers
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for TransformLoader \{org.orecruncher.dsurround.mixins.TransformLoader\}
[18:48:40] [main/DEBUG]: Running coremod plugin TransformLoader
[18:48:40] [main/DEBUG]: Coremod plugin class TransformLoader run successfully
[18:48:40] [main/DEBUG]: Injecting coremod MalisisCorePlugin \{net.malisis.core.asm.MalisisCorePlugin\} class transformers
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for MalisisCorePlugin \{net.malisis.core.asm.MalisisCorePlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin MalisisCorePlugin
[18:48:40] [main/DEBUG]: Coremod plugin class MalisisCorePlugin run successfully
[18:48:40] [main/DEBUG]: Injecting coremod MovingWorldCore \{com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod\} class transformers
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for MovingWorldCore \{com.elytradev.movingworld.common.asm.coremod.MovingWorldCoreMod\}
[18:48:40] [main/DEBUG]: Running coremod plugin MovingWorldCore
[18:48:40] [main/DEBUG]: Coremod plugin class MovingWorldCoreMod run successfully
[18:48:40] [main/DEBUG]: Injecting coremod SurgeLoadingPlugin \{net.darkhax.surge.core.SurgeLoadingPlugin\} class transformers
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for SurgeLoadingPlugin \{net.darkhax.surge.core.SurgeLoadingPlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin SurgeLoadingPlugin
[18:48:40] [main/DEBUG]: Coremod plugin class SurgeLoadingPlugin run successfully
[18:48:40] [main/DEBUG]: Injecting coremod VanillaFixLoadingPlugin \{org.dimdev.vanillafix.VanillaFixLoadingPlugin\} class transformers
[18:48:40] [main/DEBUG]: Injection complete
[18:48:40] [main/DEBUG]: Running coremod plugin for VanillaFixLoadingPlugin \{org.dimdev.vanillafix.VanillaFixLoadingPlugin\}
[18:48:40] [main/DEBUG]: Running coremod plugin VanillaFixLoadingPlugin
[18:48:40] [main/DEBUG]: Coremod plugin class VanillaFixLoadingPlugin run successfully
[18:48:40] [main/INFO]: Calling tweak class guichaguri.betterfps.tweaker.BetterFpsTweaker
[18:48:40] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:48:41] [main/DEBUG]: Validating minecraft
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: Minecraft version is 1.12.2 and BNBGamingCore accepts versions 1.12, . It will be registered.
[18:48:41] [main/INFO]: Minecraft version is 1.12.2 and BNBGamingCore accepts versions 1.12, . It will be registered.
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/patcher/IceAndFireRuntimePatcher
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.github.alexthe666.iceandfire.asm.IceAndFirePlugin.getASMTransformerClass(IceAndFirePlugin.java:18)
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:48:41] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: net/ilexiconn/llibrary/server/asm/RuntimePatcher
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 6 more
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: net.ilexiconn.llibrary.server.asm.RuntimePatcher
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:48:41] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 10 more

**Comment by CalaMariGold** [comment]
` [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/patcher/IceAndFireRuntimePatcher`

Issue with Ice and Fire. Try reinstalling Twitch and the pack. Might've gotten corrupted on download.
